name: Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx furo
    - name: Build documentation
      run: |
        cd docs
        make html
        cd ..
    - name: No jekyll
      run: touch docs/build/html/.nojekyll
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: docs/build/html
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
